name: Continuous Deployment

on:
  push:
    tags:
      - rest-v*

env:
  IMAGE_NAME: ghcr.io/openwallet-foundation/credo-rest

jobs:
  release-rest-docker-image:
    runs-on: ubuntu-latest
    steps:
      # Initiate release process if release was created
      - name: Checkout aries-framework-javascript-ext
        uses: actions/checkout@v4

      # Some packages need indy-sdk for node as part of yarn install
      - name: Setup Libindy
        uses: ./.github/actions/setup-libindy

      - name: Setup node v16
        uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org/'
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build rest package
        run: yarn workspace @credo-ts/rest build

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./packages/rest
          file: ./packages/rest/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
